# latex Makefile
ifndef texpath
texpath=/usr/texbin/
endif
PDFLATEX=${texpath}pdflatex -halt-on-error -synctex=1 --interaction=nonstopmode
SKIPERR=${texpath}pdflatex --interaction=nonstopmode
LATEX=${PDFLATEX}
BIBTEX=bibtex
DVIPS=dvips
PS2PDF=ps2pdf
SHELL=/bin/bash

all: gitstuff.tex saltydisk

.PHONY: saltydisk
saltydisk: 
	echo "texpath: ${texpath}"
	python make.py --texpath=${texpath}
	python make_apjform.py
	gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=saltydisk_compressed.pdf saltydisk.pdf
	python paper2arxiv.py --apj
	python paper2arxiv.py
	python make_apjform.py

.PHONY: diff
diff:
	python parse_macros.py saltydisk.tex saltydisk_fordiff.tex
	#python parse_macros.py saltydisk_feb13.tex submitted_fordiff.tex
	latexdiff submitted_fordiff.tex saltydisk_fordiff.tex  > diff.tex
	${SKIPERR} diff.tex
	${BIBTEX} diff
	${SKIPERR} diff.tex
	${BIBTEX} diff
	${SKIPERR} diff.tex
	gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=diff_compressed.pdf diff.pdf

.PHONY: referee
referee:
	echo "texpath: ${texpath}"
	python make.py --referee --texpath=${texpath}


gitstuff.tex: .git/logs/HEAD
	echo "%%% This file is generated by the Makefile." > gitstuff.tex
	git log -1 --date=short --format="format:\\newcommand{\\githash}{%h}\\newcommand{\\gitdate}{%ad\\xspace}\\newcommand{\\gitauthor}{%an\\xspace}" >> gitstuff.tex
